SRCS = megaphone.cpp
NAME = megaphone
CPP_FLAGS = -Wall -Wextra -Werror -std=c++98
OBJS = $(SRCS:%.cpp=%.o)

all: $(NAME)

$(NAME) : $(OBJS)
	c++ $(CPP_FLAGS) $(OBJS) -o $(NAME)

%.o: %.cpp
	c++ -c $(CPP_FLAGS) $?

clean:
	rm -rf $(OBJS)

fclean : clean
	rm -rf $(NAME)

re : fclean all

.PHONY: fclean clean re all